import Head from "next/head";
import Filters from "@/components/filters";
import TodoList from "@/components/todo-list";
import AddNewTodo from "@/components/todo-list/add-new-todo";
import TodoStats from "@/components/stats";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TodoStats />
        <br />
        <Filters />
        <br />
        <AddNewTodo />
        <br />
        <br />
        <TodoList />
      </main>
    </>
  );
}
